FROM  python:3.11.9


RUN apt-get install wget
RUN pip install pandas sqlalchemy psycopg2 pgcli requests


WORKDIR /app

COPY ingest_data.py ingest_data.py

ENTRYPOINT [ "python","ingest_data.py" ]


